/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-common-conventions")
    id("com.google.devtools.ksp") version "2.0.20-1.0.24"
}

dependencies {
    implementation(project(":annotations"))
    implementation(project(":validation"))
    implementation(project(":extension"))
    ksp(project(":annotation-processor"))
}
