/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-common-conventions")
    id("com.google.devtools.ksp") version "2.0.20-1.0.24"
}

dependencies {
    val rootName = rootProject.name.removeSuffix("-parent")
    implementation(project(":${rootName}-annotations"))
    implementation(project(":${rootName}-validation"))
    implementation(project(":${rootName}"))
    ksp(project(":${rootName}-annotation-processor"))
}
