/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-common-conventions")
    id("com.google.devtools.ksp") version "2.1.20-1.0.31"
}

dependencies {
    implementation(project(":junit-jupiter-params-generated"))
    implementation(project(":validation"))
    implementation(project(":${rootProject.name.removeSuffix("-parent")}"))
    implementation("com.willowtreeapps.assertk:assertk:0.28.1")
    ksp(project(":annotation-processor"))
}
tasks.withType<PublishToMavenRepository>().configureEach {
    enabled = false
}

dokka {
    dokkaPublications {
        configureEach { enabled = false }
    }
}
