/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    id("buildlogic.kotlin-common-conventions")
}

dependencies {
    implementation(project(":annotations"))
    implementation(project(":validation"))
    implementation("com.google.devtools.ksp:symbol-processing-api:2.0.20-1.0.24")
}
