/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    id("buildlogic.kotlin-common-conventions")
}

dependencies {
    val rootName = rootProject.name.removeSuffix("-parent")
    implementation(project(":${rootName}-annotations"))
    implementation(project(":${rootName}-validation"))
    implementation("com.google.devtools.ksp:symbol-processing-api:2.0.20-1.0.25")
}
