/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    kotlin("jvm")
    `java-library`
    id("com.vanniktech.maven.publish")
    id("org.jetbrains.dokka-javadoc")
}
group = "com.wesleyhome.test"
val versionString = providers.gradleProperty("version").get()
version = versionString

repositories {
    // Use Maven Central for resolving dependencies.
    mavenLocal()
    mavenCentral()
}
val dokkaJavadocJar: Jar by tasks.register<Jar>("javadocJar") {
    dependsOn(tasks.dokkaGenerateModuleJavadoc)
    from(tasks.dokkaGenerateModuleJavadoc.flatMap { it.outputDirectory })
    archiveClassifier.set("javadoc")
}

kotlin {
    jvmToolchain(17)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    sourceCompatibility = JavaVersion.VERSION_17
    withSourcesJar()
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

mavenPublishing {
    publishToMavenCentral(automaticRelease = true)
    signAllPublications()
    pom {
        name.set("Generated JUnit Jupiter Parameters")
        description.set("Library to help generate test parameter permutations for parameterized tests in JUnit.")
        url.set("https://junit-params.wesleyhome.com/")
        scm {
            connection.set("scm:git:https://github.com/justin-wesley/junit-jupiter-params-generated.git")
            developerConnection.set("scm:git:https://github.com/justin-wesley/junit-jupiter-params-generated.git")
            url.set("https://github.com/justin-wesley/junit-jupiter-params-generated.git")
        }
        developers {
            developer {
                id.set("justin")
                name.set("Justin Wesley")
            }
        }
        licenses {
            license {
                name.set("The Apache Software License, Version 2.0")
                url.set("https://www.apache.org/licenses/LICENSE-2.0.txt")
            }
        }
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"

    setDestinationDir(file("$buildFile/javadoc"))
    if (JavaVersion.current().isJava9Compatible) {
        (options as StandardJavadocDocletOptions).apply {
            addBooleanOption("html5", true)
        }
    }
}

