/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    id("buildlogic.kotlin-common-conventions")
}

dependencies {
    implementation(kotlin("reflect"))
    implementation(kotlin("stdlib"))
}
