name: Build Snapshot Gradle project

on:
  push:


jobs:
  build-snapshot-gradle-project:
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
      ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          ORG_GRADLE_PROJECT_signingKey: $ {{ secrets.GPG_SECRETKEY }}
          ORG_GRADLE_PROJECT_signingPassword: ""
      - name: Run build with Gradle Wrapper
        run: ./gradlew build publishToSonatype closeAndReleaseSonatypeStagingRepository
