name: Build Gradle project

on:
  push:
    tags-ignore:
      - junit*

jobs:
  build-snapshot-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build publishToSonatype closeAndReleaseSonatypeStagingRepository
