name: Build Snapshot Gradle project

on:
  push:


jobs:
  build-snapshot-gradle-project:
    runs-on: ubuntu-latest
    environment:
      name: default
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build publishToSonatype closeAndReleaseSonatypeStagingRepository
